# Master password is generated by Terraform and stored ONLY in AWS Secrets
# Manager - it is never written into a .tf file, tfvars file, or state
# output in plaintext logs.
resource "random_password" "db" {
  length  = 20
  special = true
}

resource "aws_secretsmanager_secret" "db" {
  name = "${var.cluster_name}-${var.environment}-db-credentials"
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    dbname   = var.db_name
  })
}

# Subnet group restricted to PRIVATE subnets only -> no public route to the internet
resource "aws_db_subnet_group" "this" {
  name       = "${var.cluster_name}-${var.environment}-db-subnets"
  subnet_ids = var.private_subnet_ids

  tags = { Environment = var.environment }
}

# Security group: only allows inbound Postgres (5432) from the EKS node SG.
# Nothing else, no 0.0.0.0/0 rule anywhere.
resource "aws_security_group" "db" {
  name   = "${var.cluster_name}-${var.environment}-db-sg"
  vpc_id = var.vpc_id

  ingress {
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [var.eks_node_security_group]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Environment = var.environment }
}

resource "aws_db_instance" "this" {
  identifier              = "${var.cluster_name}-${var.environment}-db"
  engine                  = "postgres"
  engine_version          = "15.17"
  instance_class          = var.db_instance_class
  allocated_storage       = 20
  storage_encrypted       = true
  db_name                 = var.db_name
  username                = var.db_username
  password                = random_password.db.result
  db_subnet_group_name    = aws_db_subnet_group.this.name
  vpc_security_group_ids  = [aws_security_group.db.id]

  # This is the key control: no public IP, no public accessibility
  publicly_accessible     = false

  multi_az                = var.environment == "production"
  backup_retention_period = 7
  deletion_protection     = var.environment == "production"
  skip_final_snapshot     = var.environment != "production"

  tags = { Environment = var.environment }
}

# Private DNS: EKS pods resolve this private hosted zone entry instead of a
# public FQDN so the database hostname never leaves the VPC's private DNS.
resource "aws_route53_zone" "private" {
  name = "internal.${var.cluster_name}.local"

  vpc {
    vpc_id = var.vpc_id
  }
}

resource "aws_route53_record" "db" {
  zone_id = aws_route53_zone.private.zone_id
  name    = "db.internal.${var.cluster_name}.local"
  type    = "CNAME"
  ttl     = 300
  records = [aws_db_instance.this.address]
}
